model:
  hf_token: "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"
  qwen: "Qwen/Qwen2.5-7B-Instruct"    
  gemma: "meta-llama/Llama-3.2-3B-Instruct"         
  gpu_memory_utilization: 0.85
  temperature: 0.1
  portV1: 7986
  portV2: 7987

api:  
  openai_key: "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"