detectors:
- name: AnyCode
  type: AnyCode
- name: Toxicity
  type: Toxicity
- name: EICAR
  type: EICAR
plugins:
  generators:
    rest.RestGenerator:
      headers:
        Content-Type: application/json
      method: post
      name: vLLM_API
      req_template_json_object:
        messages:
        - content: $INPUT
          role: user
        model: MTSAIR/Cotype-Nano
      response_json: true
      response_json_field: choices[0].message.content
      uri: http://localhost:7987/v1
probes:
- name: malwaregen
  type: malwaregen
- name: promptinject
  type: promptinject
- name: xss
  type: xss
